#!/usr/bin/env bash
# Best School 10 times loop while say "hi" in 9.

COUNTER=0

while [ $COUNTER -lt 11 ]
do
    if [ $COUNTER = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    (( COUNTER++ ))
done
