#!/usr/bin/env bash
# Best School 10 times.
# bad luck for the 4th loop iteration
# good luck for the 8th loop iteration
# Best School for the other iterations
COUNTER=0
while [ $COUNTER -lt 10 ]
do
    if [ $COUNTER = 4 ]
    then
        echo "bad luck"
    elif [ $COUNTER = 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    (( COUNTER++ ))
done
