#!/usr/bin/env bash
# displays numbers from 1 to 20.
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration

COUNTER=0

while [ $COUNTER -lt 20 ]
do
    case $COUNTER in

        4)
	    echo $COUNTER
	    echo "bad luck from China"
	    ;;
	
	9)
	    echo $COUNTER
	    echo "bad luck from Japan"
	    ;;
	
	17)
	    echo $COUNTER
	    echo "bad luck from Italy"
	    ;;

	*)
	    echo $COUNTER
	    ;;
    esac

    (( COUNTER++ ))
done
